version: 2.1
orbs:
    php: circleci/php@1.1.0

jobs:
  build:
    executor: php/default
    steps:
      - checkout
      - php/install-php:
          version: '8.1'
      - php/install-composer:
          install-version: '2.4.3'
      - run:
          name: Extra PHP packages
          command: |
            sudo apt-get install -y php8.1-xml php8.1-yaml php8.1-mbstring php8.1-xdebug
      - run:
          name: Composer Install
          command: php8.1 /usr/local/bin/composer install
      - run:
          name: PHPUnit
          command: XDEBUG_MODE=coverage php8.1 ./vendor/bin/phpunit --coverage-clover coverage.xml
      - run:
          name: Code coverage
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov 
      - run:
          name: Execute
          command: php8.1 ./bin/app checkBoards < tests/fixtures/input.txt
      - run:
          name: Compare command output with expected output
          command: diff -u tests/fixtures/output.txt <(php8.1 ./bin/app checkBoards < tests/fixtures/input.txt)
